### ISSUE TITLE
The Raw SerenityScore value keeps changing when I add User scores to a zipcode.

### ISSUE THREAD

**Issue by matthewgabriele94** [gcivil-nyu-org/INET-Team-2-F2022#73]
I was playing around with adding User scores to zipcode 11220, and I noticed that while I was doing this, the Raw SerenityScore kept changing (see screenshots below). I'm actually not sure if this even has anything to do with me adding User scores, but it seems like the Tree Census score keeps changing every time I click on the page for that zipcode, and that might be driving the changes to the Raw SerenityScore.

EDIT: This may have to do with the last bullet point in your "not to test" list - I wasn't sure but thought I'd include this just in case. But if it is, disregard this.
![Screen Shot 2022-11-26 at 10 48 25 PM](https://user-images.githubusercontent.com/85814772/204118468-40b62b8d-a63a-43a5-82f5-0a6a4b2df986.png)
![Screen Shot 2022-11-26 at 10 49 08 PM](https://user-images.githubusercontent.com/85814772/204118469-a1f6bc61-0ce5-4b50-a984-8855be6d8c99.png)
![Screen Shot 2022-11-26 at 10 51 35 PM](https://user-images.githubusercontent.com/85814772/204118471-65da518d-5425-496b-8fe1-4f5fb03f9f7e.png)

**Comment by jgaomcintosh** [comment]
Issue: Tree Census factor was displaying the raw User Score, and Parks Properties factor was displaying the Tree Census score within search results page. This was due to the omission of a small counter/increment within a loop which looped through all factors (skipping User Score) when returning values from the ScoreTable database to print.

Resolution: Add an incremental step within the else statement of a loop.

The screenshots below show the search results page before and after rating zip code 11210 with a D. We can see that now only the User Rating changes:

<img width="736" alt="Screen Shot 2022-11-27 at 10 04 41 AM" src="https://user-images.githubusercontent.com/102495313/204142325-d31cd6c6-a1c1-4dcf-b5a8-1637f5f0c560.png">

<img width="785" alt="Screen Shot 2022-11-27 at 10 05 28 AM" src="https://user-images.githubusercontent.com/102495313/204142336-b47bc9c7-21da-48a1-a5b3-c03659e1aa94.png">
